# Generated by Django 4.2.5 on 2023-09-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retailer", models.CharField(max_length=200)),
                ("purchaseDate", models.DateField()),
                ("purchaseTime", models.TimeField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shortDescription", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "receipt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receipt_processor.receipt",
                    ),
                ),
            ],
        ),
    ]
