# Generated by Django 4.2.5 on 2023-09-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt", name="points", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="items", name="price", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="receipt", name="total", field=models.FloatField(),
        ),
    ]
