# Generated by Django 4.2.5 on 2023-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receipt_processor",
            "0002_receipt_points_alter_items_price_alter_receipt_total",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
